In [247]:
#Q1 list to 1d array 
import numpy as np
list = [12.23, 13.32, 100, 36.32]

nd_array = np.array(list)
print(nd_array)
print(nd_array.ndim) #this shows the dimension of the array 

[ 12.23  13.32 100.    36.32]
1


In [16]:
#Q2 3x3 matrix 
import numpy as np 

matrix = np.arange(2, 11).reshape(3,3)
matrix 

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [20]:
#Q3 Null vector 
import numpy as np 
eleventh_zero = np.zeros(10) #this displays 1d array filled with zeros
print(eleventh_zero)
eleventh_zero[5] = 11 #this will update the 6th value to 11
print(eleventh_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [27]:
#Q4 Array from 12 to 38 
import numpy as np 

arr = np.arange(12, 38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [42]:
#Q5 Converting from Array to Float type 
import numpy as np 

arr = np.array([1, 2, 3, 4]) #original array with int type 
print(arr) 
print(arr.dtype)

float_type_arr = arr.astype(float) #float type array 
print(float_type_arr)
print(float_type_arr.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64


In [54]:
#Q6 Celcius to Farenheit 
import numpy as np 

#defining the arrays 
sample_arr = [0, 12, 45.21, 34, 99.91] 
sample_arr1 = [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

#converting from celcius to farenheit
celcius = np.array(sample_arr)
farenheit = (celcius * 9/5) + 32 
print(f'Temperature in farenheit: {farenheit}') #printing part 

celcius1 = np.array(sample_arr1)
farenheit1 = (celcius1 * 9/5) +32 
print(f'Temperature in farenheit: {farenheit1}') #printing part 

Temperature in farenheit: [ 32.     53.6   113.378  93.2   211.838]
Temperature in farenheit: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [63]:
#Q7 Appending values to array 
import numpy as np 

arr = np.array([10, 20, 30]) #original array 
print(arr) 

app_val = np.arange(40, 100, 10)
appended_arr = np.append(arr, app_val) #appended array 
print(appended_arr) 

[10 20 30]
[10 20 30 40 50 60 70 80 90]


In [172]:
#Q8 Array statistical functions 
import numpy as np 

random_array = np.random.randint(1, 100, 10) #original array of numbers 
print(random_array)

mean_value = np.mean(random_array)
print(f'Mean value: {mean_value}')

median_value= np.median(random_array)
print(f'Median value: {median_value}') 

standard_deviation = np.std(random_array)
print(f'Standard deviation: {standard_deviation}')

[20 14 72 16 77 85  2 38 81 77]
Mean value: 48.2
Median value: 55.0
Standard deviation: 31.457272609048612


In [215]:
#Q9 Min and Max values in array 
import numpy as np 

random_array = np.random.randn(10, 10)
#print(random_array)

min_arr = np.min(random_array)
print(f'Minimum value = {min_arr}')

max_arr = np.max(random_array)
print(f'Maximum value = {max_arr}')

Minimum value = -2.603644852746531
Maximum value = 1.3529699610880985


In [246]:
#Q10 3x3x3 array with random values 
import numpy as np

ran_values = np.random.randn(3, 3, 3)
print(ran_values)

[[[-1.02697191  0.23211694 -0.18114694]
  [ 0.73274842 -0.1910422  -0.69907732]
  [-1.79854467 -1.69377438  0.46930513]]

 [[ 1.70264342 -1.26546063 -0.36241912]
  [-1.11519546 -0.03380963 -1.74959618]
  [-2.54170424 -2.15908643 -1.16867437]]

 [[ 0.66301778 -1.13401129  0.54179616]
  [-0.22029099  1.26913069  0.03046501]
  [-0.44612501  0.31476087  0.66566472]]]
